### ISSUE TITLE
No explanation for what DESCRIPTION should contain

### ISSUE THREAD

**Issue by schroedey** [mntnr/audit-templates#4]
Per audits Richard has done, it seems this should be the description of the repo being audited.  Also, Richard seems to excise the link in the source repo's description when he does this.  Is that intentional?

**Comment by RichardLitt** [comment]
You can probably either use @RichardLitt or just say 'you' instead of using the third person. :D 

Yes. `DESCRIPTION` is simply a stand in to be replaced with the GitHub description, which doesn't include the link next to it, normally. We could include the link separately, actually, but I haven't historically.
